-- 004_qr_management.sql
alter table public.qr_codes add column if not exists series_name text;
alter table public.qr_codes add column if not exists series_sequence integer;
alter table public.qr_codes add column if not exists assigned_at timestamptz;
alter table public.qr_codes add column if not exists revoked_at timestamptz;
create unique index if not exists qr_codes_product_sequence_unique on public.qr_codes(product_id,series_sequence) where series_sequence is not null;
create index if not exists qr_codes_series_idx on public.qr_codes(seller_id,product_id,series_name);
create or replace function public.qr_product_prefix(requested_name text) returns text language plpgsql immutable as $$ declare cleaned text; begin cleaned:=upper(regexp_replace(coalesce(requested_name,''),'[^A-Za-z0-9]+','-','g')); cleaned:=trim(both '-' from cleaned); cleaned:=left(cleaned,12); if cleaned='' then cleaned:='QR'; end if; return cleaned; end; $$;
create or replace function public.generate_qr_series(requested_product_id uuid,requested_series_name text,requested_quantity integer) returns integer language plpgsql security definer set search_path=public as $$ declare current_seller_id uuid:=auth.uid(); product_record public.products%rowtype; prefix text; next_sequence integer; i integer; generated_count integer:=0; begin if current_seller_id is null then raise exception 'Authentication required'; end if; if requested_quantity is null or requested_quantity<1 or requested_quantity>5000 then raise exception 'Quantity must be between 1 and 5000'; end if; if requested_series_name is null or length(trim(requested_series_name))=0 then raise exception 'Series name is required'; end if; select * into product_record from public.products where id=requested_product_id and seller_id=current_seller_id and is_active=true; if not found then raise exception 'Product not found'; end if; perform pg_advisory_xact_lock(hashtext(requested_product_id::text)); select coalesce(max(series_sequence),0)+1 into next_sequence from public.qr_codes where product_id=requested_product_id; prefix:=public.qr_product_prefix(product_record.name); for i in 0..requested_quantity-1 loop insert into public.qr_codes(seller_id,product_id,code,public_token,series_name,series_sequence,status,created_at) values(current_seller_id,requested_product_id,prefix||'-'||lpad((next_sequence+i)::text,4,'0'),replace(gen_random_uuid()::text,'-',''),trim(requested_series_name),next_sequence+i,'available',now()); generated_count:=generated_count+1; end loop; return generated_count; end; $$;
revoke all on function public.generate_qr_series(uuid,text,integer) from public; grant execute on function public.generate_qr_series(uuid,text,integer) to authenticated; alter table public.qr_codes enable row level security; revoke all on public.qr_codes from anon; grant select on public.qr_codes to authenticated; drop policy if exists "qr_select_own" on public.qr_codes; create policy "qr_select_own" on public.qr_codes for select to authenticated using(seller_id=(select auth.uid()));
